# Generated by Django 4.2.10 on 2024-02-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Lab1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("name", models.CharField(max_length=50)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(max_length=50)),
            ],
        ),
    ]
