# Generated by Django 4.2.10 on 2024-02-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Lab1", "0002_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="my_users",
        ),
    ]
