# Generated by Django 4.2.10 on 2024-02-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Lab1", "0004_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
